# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SKSugarSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKSugarSwiftExample

  # pod 'SKSugarSwift'
  pod 'SnapKit'








  target 'SKSugarSwiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SKSugarSwiftExampleUITests' do
    # Pods for testing
  end

end
