# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'







target 'SKSugarSwiftTestOfOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKSugarSwiftTestOfOC
  
  pod 'SKSugarSwift'
  
  
  
  
  

  target 'SKSugarSwiftTestOfOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SKSugarSwiftTestOfOCUITests' do
    # Pods for testing
  end

end
